# to activate/deactivate travisCI - go to https://travis-ci.org/, sign
# in with guthub, and follow instructions

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - ./test.py

notifications:
  email:
    - noah.hoffman@gmail.com
